load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "go_default_library",
    srcs = ["stress.go"],
    importpath = "github.com/jackskj/schematic/stresstest/stress",
    visibility = ["//visibility:public"],
)
