# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pb/schematic.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='pb/schematic.proto',
  package='pb',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x12pb/schematic.proto\x12\x02pb\"A\n\x06Schema\x12\r\n\x05topic\x18\x01 \x01(\t\x12\x0f\n\x07version\x18\x02 \x01(\t\x12\x17\n\x0f\x66ile_descriptor\x18\x03 \x01(\x0c\"+\n\tSchemaReq\x12\r\n\x05topic\x18\x01 \x01(\t\x12\x0f\n\x07version\x18\x02 \x01(\t\"\x0f\n\rEmptyResponse2h\n\tSchematic\x12\x31\n\x0eRegisterSchema\x12\n.pb.Schema\x1a\x11.pb.EmptyResponse\"\x00\x12(\n\tGetSchema\x12\r.pb.SchemaReq\x1a\n.pb.Schema\"\x00\x62\x06proto3')
)




_SCHEMA = _descriptor.Descriptor(
  name='Schema',
  full_name='pb.Schema',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='topic', full_name='pb.Schema.topic', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='version', full_name='pb.Schema.version', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='file_descriptor', full_name='pb.Schema.file_descriptor', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=91,
)


_SCHEMAREQ = _descriptor.Descriptor(
  name='SchemaReq',
  full_name='pb.SchemaReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='topic', full_name='pb.SchemaReq.topic', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='version', full_name='pb.SchemaReq.version', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=93,
  serialized_end=136,
)


_EMPTYRESPONSE = _descriptor.Descriptor(
  name='EmptyResponse',
  full_name='pb.EmptyResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=138,
  serialized_end=153,
)

DESCRIPTOR.message_types_by_name['Schema'] = _SCHEMA
DESCRIPTOR.message_types_by_name['SchemaReq'] = _SCHEMAREQ
DESCRIPTOR.message_types_by_name['EmptyResponse'] = _EMPTYRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Schema = _reflection.GeneratedProtocolMessageType('Schema', (_message.Message,), {
  'DESCRIPTOR' : _SCHEMA,
  '__module__' : 'pb.schematic_pb2'
  # @@protoc_insertion_point(class_scope:pb.Schema)
  })
_sym_db.RegisterMessage(Schema)

SchemaReq = _reflection.GeneratedProtocolMessageType('SchemaReq', (_message.Message,), {
  'DESCRIPTOR' : _SCHEMAREQ,
  '__module__' : 'pb.schematic_pb2'
  # @@protoc_insertion_point(class_scope:pb.SchemaReq)
  })
_sym_db.RegisterMessage(SchemaReq)

EmptyResponse = _reflection.GeneratedProtocolMessageType('EmptyResponse', (_message.Message,), {
  'DESCRIPTOR' : _EMPTYRESPONSE,
  '__module__' : 'pb.schematic_pb2'
  # @@protoc_insertion_point(class_scope:pb.EmptyResponse)
  })
_sym_db.RegisterMessage(EmptyResponse)



_SCHEMATIC = _descriptor.ServiceDescriptor(
  name='Schematic',
  full_name='pb.Schematic',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=155,
  serialized_end=259,
  methods=[
  _descriptor.MethodDescriptor(
    name='RegisterSchema',
    full_name='pb.Schematic.RegisterSchema',
    index=0,
    containing_service=None,
    input_type=_SCHEMA,
    output_type=_EMPTYRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetSchema',
    full_name='pb.Schematic.GetSchema',
    index=1,
    containing_service=None,
    input_type=_SCHEMAREQ,
    output_type=_SCHEMA,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_SCHEMATIC)

DESCRIPTOR.services_by_name['Schematic'] = _SCHEMATIC

# @@protoc_insertion_point(module_scope)
