//
// DO NOT EDIT.
//
// Generated by the protocol buffer compiler.
// Source: pb/collector.proto
//

//
// Copyright 2018, gRPC Authors All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
import Foundation
import GRPC
import NIO
import NIOHTTP1
import SwiftProtobuf


/// Usage: instantiate Pb_CollectorClient, then call methods of this protocol to make API calls.
internal protocol Pb_CollectorClientProtocol {
  func streamRecords(callOptions: CallOptions?) -> ClientStreamingCall<Pb_Record, Pb_Ack>
  func putRecord(_ request: Pb_Record, callOptions: CallOptions?) -> UnaryCall<Pb_Record, Pb_Ack>
}

internal final class Pb_CollectorClient: GRPCClient, Pb_CollectorClientProtocol {
  internal let channel: GRPCChannel
  internal var defaultCallOptions: CallOptions

  /// Creates a client for the pb.Collector service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  internal init(channel: GRPCChannel, defaultCallOptions: CallOptions = CallOptions()) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
  }

  /// Asynchronous client-streaming call to StreamRecords.
  ///
  /// Callers should use the `send` method on the returned object to send messages
  /// to the server. The caller should send an `.end` after the final message has been sent.
  ///
  /// - Parameters:
  ///   - callOptions: Call options; `self.defaultCallOptions` is used if `nil`.
  /// - Returns: A `ClientStreamingCall` with futures for the metadata, status and response.
  internal func streamRecords(callOptions: CallOptions? = nil) -> ClientStreamingCall<Pb_Record, Pb_Ack> {
    return self.makeClientStreamingCall(path: "/pb.Collector/StreamRecords",
                                        callOptions: callOptions ?? self.defaultCallOptions)
  }

  /// Asynchronous unary call to PutRecord.
  ///
  /// - Parameters:
  ///   - request: Request to send to PutRecord.
  ///   - callOptions: Call options; `self.defaultCallOptions` is used if `nil`.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func putRecord(_ request: Pb_Record, callOptions: CallOptions? = nil) -> UnaryCall<Pb_Record, Pb_Ack> {
    return self.makeUnaryCall(path: "/pb.Collector/PutRecord",
                              request: request,
                              callOptions: callOptions ?? self.defaultCallOptions)
  }

}

/// To build a server, implement a class that conforms to this protocol.
internal protocol Pb_CollectorProvider: CallHandlerProvider {
  func streamRecords(context: UnaryResponseCallContext<Pb_Ack>) -> EventLoopFuture<(StreamEvent<Pb_Record>) -> Void>
  func putRecord(request: Pb_Record, context: StatusOnlyCallContext) -> EventLoopFuture<Pb_Ack>
}

extension Pb_CollectorProvider {
  internal var serviceName: String { return "pb.Collector" }

  /// Determines, calls and returns the appropriate request handler, depending on the request's method.
  /// Returns nil for methods not handled by this service.
  internal func handleMethod(_ methodName: String, callHandlerContext: CallHandlerContext) -> GRPCCallHandler? {
    switch methodName {
    case "StreamRecords":
      return ClientStreamingCallHandler(callHandlerContext: callHandlerContext) { context in
        return self.streamRecords(context: context)
      }

    case "PutRecord":
      return UnaryCallHandler(callHandlerContext: callHandlerContext) { context in
        return { request in
          self.putRecord(request: request, context: context)
        }
      }

    default: return nil
    }
  }
}


// Provides conformance to `GRPCPayload` for request and response messages
extension Pb_Record: GRPCProtobufPayload {}
extension Pb_Ack: GRPCProtobufPayload {}

